# Generated by Django 4.2.1 on 2023-08-12 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0002_article_tag_comment_article_taglist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveField(
            model_name='tag',
            name='createdAt',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='updatedAt',
        ),
        migrations.AddField(
            model_name='tag',
            name='tag',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
