# Generated by Django 4.2.1 on 2023-08-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0003_alter_tag_options_remove_tag_createdat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag',
            field=models.SlugField(unique=True),
        ),
    ]
