# Generated by Django 4.2.1 on 2023-08-12 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('endpoint', '0004_remove_tag_slug_alter_tag_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='favorities',
            new_name='favorites',
        ),
        migrations.AlterField(
            model_name='article',
            name='tagList',
            field=models.ManyToManyField(blank=True, to='endpoint.tag'),
        ),
    ]
